[client]
showErrorDetails = "none"

[theme]
primaryColor = "purple"
backgroundColor = "black"
textColor = "white"
base = "dark"
secondaryBackgroundColor = "#000435"
[theme.sidebar]
backgroundColor = "brown"
